### ISSUE TITLE
AttributeError when restoring

### ISSUE THREAD

**Issue by alexfederlin** [tasmota/decode-config#19]
**Describe the bug**
When trying to restore a JSON config to a device, the following error message appears:
`$ python3 decode-config.py -S --dry-run -e -s http://admin:Tasmota@192.168.2.193 -i Config_sonoff_315698_5784_8.1.0_ori.conf
Traceback (most recent call last):
  File "decode-config.py", line 4768, in <module>
    restore(ARGS.restorefile, ARGS.backupfileformat, CONFIG)
  File "decode-config.py", line 4235, in restore
    new_decode_cfg = mapping2bin(config, jsonconfig, restorefilename)
  File "decode-config.py", line 4053, in mapping2bin
    set_field(_buffer, 1<<config['info']['platform'], name, setting_fielddef, data, addroffset=0, filename=filename)
  File "decode-config.py", line 3653, in set_field
    restoremap = restoremapping.get(name, None)
AttributeError: 'str' object has no attribute 'get'
`

**To Reproduce**
1. Download a Config dump
2. decode it using `python3 decode-config.py -s Config_sonoff_315698_5784_8.1.0.dmp -o Config_sonoff_315698_5784_8.1.0_ori.conf`
3. Try to restore the config back to the device using command stated above

**Expected behavior**
Config restored to device

**Version Information (please complete the following information):**
- decode-config: [e.g. use `decode-config -VV` to retrieve the info]:  
```
decode-config.py v8.4.0 [00067] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.6.9
Platform: Linux-4.15.0-109-generic-x86_64-with-Ubuntu-18.04-bionic - x86_64
OS:       Linux 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020
Time:     2020-08-12 14:29:50

```
- 'system' information of your Tasmota data (append `-g System` to your decode-config parameter, e. g. `decode-config -f myconfig.dmp -g System`):  
```
$ python3 decode-config.py -f Config_sonoff_315698_5784_8.1.0.dmp -g System
{"bootcount": 9, "cfg_crc": "0x9453", "cfg_crc32": "0xad5ab1e8", "cfg_holder": 4618, "cfg_size": 4096, "cfg_timestamp": 1597226542, "header": {"data": {"crc": "0xdaa8", "crc32": "0xad5ab1e8", "size": 4096, "template": {"crc": "0x9453", "crc32": "0xad5ab1e8", "size": 4096, "version": "0x8010000"}, "version": "0x8010000"}, "env": {"platform": "Linux-4.15.0-109-generic-x86_64-with-Ubuntu-18.04-bionic", "python": "3.6.9", "script": "decode-config.py v8.4.0 [00067]", "system": "Linux x86_64 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020"}, "timestamp": "2020-08-12 10:02:22"}, "version": "0x8010000"}
```

**Additional context**
_Add any other context about the problem here._

**Comment by curzon01** [comment]
sorry, can not reproduce (Tasmota 8.1.0, decode-config v8.4.0 [00067]). Are you able to provide your json? (e.g. via [mail](mailto:norbert.richter@prsolution.eu) or [discord](https://discord.gg/Ks2Kzd4) PM @curzon01)

**Comment by alexfederlin** [comment]
Mail sent

**Comment by curzon01** [comment]
strange, still not reproducable:

```
$ python3.6 ./decode-config.py -VV
decode-config.py v8.4.0 [00067] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.6.9
Platform: Linux-5.4.0-42-generic-x86_64-with-LinuxMint-20-ulyana - x86_64
OS:       Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
Time:     2020-08-14 10:30:50

```
using device havong Tasmota v8.1.0

$ python3.6 ./decode-config.py --dry-run -e -s http://admin:Tasmota@172.18.10.242 -i Config_sonoff_315698_5784_8.1.0_ori.conf
Load data from device '172.18.10.242'
** Simulating ** Restore successful to device '172.18.10.242' from './Config_sonoff_315698_5784_8.1.0_ori.conf'

same for the file

$ python3.6 ./decode-config.py --dry-run -e -s Config_sonoff_315698_5784_8.1.0.dmp -i Config_sonoff_315698_5784_8.1.0_ori.conf
Load data from file 'Config_sonoff_315698_5784_8.1.0.dmp'
Restore skipped, configuration data unchanged

**Comment by curzon01** [comment]
any news?

**Comment by alexfederlin** [comment]
Sorry. Here goes:

Release Binary fails:

```
$ ./decode-config_linux 
[14921] Error loading Python lib '/tmp/_MEIRMI1sx/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIRMI1sx/libpython3.8.so.1.0)
```

module versions:
```python3 -c 'import json;import requests;print("json: {}".format(json.__version__));print("requests: {}".format(requests.__version__))'
json: 2.0.9
requests: 2.23.0
```

**Comment by curzon01** [comment]
the origin issue is related to a corrupt python environment 
this is a result installing python/libs mixed by `apt-get` and `python -m pip` also using `python -m pip` mixed with and without sudo
For example on Ubuntu 18.04.5 LTS bionic `requests` lib is 2.18.4 not 2.23.0

- check `ls -la /usr/bin/python*` to see how many python version are installed
- check `update-alternatives --list python3` if altenatives
- try python3.8 instead

I will check in parallel to create a binary which works on 18.04 more stable...

**Comment by curzon01** [comment]
pls try attached binary which was created under Ubuntu 18.04.5 LTS bionic

[decode-config_linux.zip](https://github.com/tasmota/decode-config/files/5094653/decode-config_linux.zip)

**Comment by alexfederlin** [comment]
The binaries in and of themselves can now be executed.
However, when called in conjunction with the original config file, I still get the same errors.

I even tried in a ubuntu 18.04.5 environment (fresh installed vagrant bento/ubuntu-18.04). Same result:
```
vagrant@vagrant:/vagrant$ ./decode-config_linux2 -s http://admin:Tasmota@tasmota_755f13-7955/ -i Config_sonoff_315698_5784_8.1.0_ori.conf
Load data from device 'tasmota_755f13-7955'
Traceback (most recent call last):
  File "decode-config.py", line 4768, in <module>
  File "decode-config.py", line 4235, in restore
  File "decode-config.py", line 4053, in mapping2bin
  File "decode-config.py", line 3653, in set_field
AttributeError: 'str' object has no attribute 'get'
[53149] Failed to execute script decode-config
```
Same for 20.04, BTW...

**Comment by curzon01** [comment]
just fresh installed Ubuntu 18.04.5 Server iso from https://releases.ubuntu.com/18.04/ on a clean disk in VirtualBox using your config file sent

```bash
$sha256sum Config_sonoff_315698_5784_8.1.0.dmp
acf88a5cb3e37753ef1c8a43961835066c333e1ff82cb11d91132dd65eaf55a1  Config_sonoff_315698_5784_8.1.0.dmp
$ sha256sum Config_sonoff_315698_5784_8.1.0_ori.conf 
278e5377f5f5af9bac9edb9f34d6e88f58503b42355678caeae836ad90c0a061  Config_sonoff_315698_5784_8.1.0_ori.conf
```

```bash
$ sudo apt install python3 python3-pip
$ python3 -m pip install requests configargparse
```

still no issue here

```bash
./decode-config_linux2 -VV
decode-config_linux1 v8.4.0 [00067] by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.6.9
Platform: Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic - x86_64
OS:       Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020
Time:     2020-08-20 06:57:00
```

```bash
./decode-config_linux2 -s http://admin:Tasmota@172.18.10.242 -i Config_sonoff_315698_5784_8.1.0_ori.conf
Load data from device '172.18.10.242'
Restore successful to device '172.18.10.242' from './Config_sonoff_315698_5784_8.1.0_ori.conf'
```

**Comment by curzon01** [comment]
as I can't reproduce it, pls use the attached version which has some debug output when error occurs

[decode-config.py.zip](https://github.com/tasmota/decode-config/files/5101921/decode-config.py.zip)

**Comment by alexfederlin** [comment]
Thanks for keeping at it.
This is the output the debug script generated:
[debug.log](https://github.com/tasmota/decode-config/files/5105193/debug.log)

Again, run on a fresh Ubuntu 18.04. I only had to run `sudo apt install python3-configargparse`
Just to be on the safe side, here's the version info:

```
vagrant@vagrant:/vagrant$ python3 decode-config.py -VV
decode-config.py v8.4.0 [00067] - debug by Norbert Richter <nr@prsolution.eu>

Script:   decode-config.py
Python:   3.6.9
Platform: Linux-4.15.0-112-generic-x86_64-with-Ubuntu-18.04-bionic - x86_64
OS:       Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020
Time:     2020-08-20 19:59:33
vagrant@vagrant:/vagrant$ python3 -c 'import json;import requests;print("json: {}".format(json.__version__));print("requests: {}".format(requests.__version__))'
json: 2.0.9
requests: 2.18.4

```

**Comment by curzon01** [comment]
one step further

your run seems to process a wrong settings template version >8.1.0
there are fields processing that do not exist in v8.1.0 - but I cannot explain why this occurs with your run

So I may ask you again to pre-check the following
- does your device tasmota_755f13-7955 really have v8.1.0?
- please confirm the sha256sum from above (so that we really use the same files)  
```
$sha256sum Config_sonoff_315698_5784_8.1.0.dmp
acf88a5cb3e37753ef1c8a43961835066c333e1ff82cb11d91132dd65eaf55a1  Config_sonoff_315698_5784_8.1.0.dmp
$ sha256sum Config_sonoff_315698_5784_8.1.0_ori.conf 
278e5377f5f5af9bac9edb9f34d6e88f58503b42355678caeae836ad90c0a061  Config_sonoff_315698_5784_8.1.0_ori.conf
```

please start the attached extended debug version with additional parameters `-v --debug`:

`python3 ./decode-config.py --dry-run -s http://admin:Tasmota@tasmota_755f13-7955/ -i 
Config_sonoff_315698_5784_8.1.0_ori.conf -v --debug`

[decode-config.py.zip](https://github.com/tasmota/decode-config/files/5107794/decode-config.py.zip)
